"""Template schemas for direct structured output from domain agents."""

from services.tstation.agents.templates.schemas import (
    CheapestItem,
    CheapestProductDataEvent,
    CheapestProductTemplate,
    CarItem,
    CarMeta,
    DataEvent,
    DiscoveryDataEvent,
    ListCarDataEvent,
    ListCarTemplate,
    PreviewYoutubeDataEvent,
    PreviewYoutubeTemplate,
    ProductDataEvent,
    ProductItem,
    ProductMeta,
    ProductTemplate,
    QnaCompleteDataEvent,
    QnaCompleteTemplate,
    QuickReplyDataEvent,
    QuickReplyTemplate,
    RedictLink,
    SupportDataEvent,
    TemplatePayload,
    TransactionDataEvent,
    YoutubeItem,
)

__all__ = [
    "CarItem",
    "CarMeta",
    "CheapestItem",
    "CheapestProductDataEvent",
    "CheapestProductTemplate",
    "DataEvent",
    "DiscoveryDataEvent",
    "ListCarDataEvent",
    "ListCarTemplate",
    "PreviewYoutubeDataEvent",
    "PreviewYoutubeTemplate",
    "ProductDataEvent",
    "ProductItem",
    "ProductMeta",
    "ProductTemplate",
    "QnaCompleteDataEvent",
    "QnaCompleteTemplate",
    "QuickReplyDataEvent",
    "QuickReplyTemplate",
    "RedictLink",
    "SupportDataEvent",
    "TemplatePayload",
    "TransactionDataEvent",
    "YoutubeItem",
]
